site_name: Vedgie Net
site_description: Cale's homepage
site_url: https://vedgie.net

theme:
  name: material
  logo: static/icons/grass.svg
  favicon: static/icons/grass.svg

plugins:
  - search
  - gen-files:
      scripts:
        - gen_writing_index.py

nav:
  - Home: index.md
  - Bio: bio.md
  - Media: media.md
  - Writing: writing/index.md
  - Reading: reading/index.md

markdown_extensions: 
  - footnotes

extra_css:
  - static/extra.css

extra:
  analytics:
    provider: google
    property: G-TW5TXJBYF5
  generator: false
